LMS/LMS/Controllers/LetterSendingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Net.Mail;
using LMS.Models;
using System.IO;
using LMS.Context;
using System.Data.Entity;

namespace LMS.Controllers
{
    public class LetterSendingController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        // GET: LetterSending
        [HttpGet]
        public ActionResult IncomingLetter()
        {
            LetterViewModel letterviewmodel = new LetterViewModel();
            using (LetterManagementDBEntities db = new LetterManagementDBEntities())
            {
                List<LetterFrom> letterfrom = new List<LetterFrom>();
                letterfrom = db.LetterFroms.ToList();
                List<LetterType> lettertype = new List<LetterType>();
                lettertype = db.LetterTypes.ToList();
                List<Designation> desingnation = new List<Designation>();
                desingnation = db.Designations.ToList();
                List<LetterStatu> letterStatu = new List<LetterStatu>();
                letterStatu = db.LetterStatus.ToList();

                ViewBag.letterfromList = new SelectList(letterfrom, "LetterSender", "LetterSender");
                ViewBag.LettertypeList = new SelectList(lettertype, "TypeOfLetter", "TypeOfLetter");
                ViewBag.designationList = new SelectList(desingnation, "Name", "Name");
                ViewBag.letterStatusList = new SelectList(letterStatu, "Status", "Status");
            }
            return View();
        }
        [HttpPost]
        public  ActionResult IncomingLetter(LetterViewModel model)
        {
            //if (ModelState.IsValid)
            {

                Letter letter = new Letter();
                letter.Sender = model.Sender;
                letter.Responsible = model.Responsible;
                letter.Subject = model.Subject;
                letter.ReferenceNo = model.ReferenceNo;
                letter.LetterDate = model.LetterDate;
                letter.ReceiveDate = model.ReceiveDate;
                letter.Type = model.Type;
                letter.StatusOfLetter = model.StatusOfLetter;

                string fileName = Path.GetFileNameWithoutExtension(model.ImageFile.FileName);
                string extension = Path.GetExtension(model.ImageFile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                letter.ScannedImage = "~/UploadedFiles/" + fileName;
                fileName = Path.Combine(Server.MapPath("~/UploadedFiles/"), fileName);
                model.ImageFile.SaveAs(fileName);


                using (LetterManagementDBEntities db= new LetterManagementDBEntities())
                {
                    db.Letters.Add(letter);
                    db.SaveChanges();
                }
                return View("Index");
            }
           // ModelState.Clear();
             return View(model);           
        }
        [HttpGet]
        public ActionResult ViewAllIncomingLetter()
        {           
            using (LetterManagementDBEntities dc = new LetterManagementDBEntities())
            {   
                var IncomingLetters = dc.Letters.ToList();
                return Json(new { data = IncomingLetters }, JsonRequestBehavior.AllowGet);

            }

        }
        [HttpGet]
        public ActionResult Commentpopup(int id)
        {
            Letter letter = new Letter();
            using (LetterManagementDBEntities db = new LetterManagementDBEntities())
            {               
                letter = db.Letters.Where(x => x.Id == id).FirstOrDefault();
                ViewBag.ReferenceNo = letter.ReferenceNo;
                ViewBag.Responsible = letter.Responsible;
                ViewBag.DateOfToday = DateTime.Today;
                List<Designation> desingnation = new List<Designation>();
                desingnation = db.Designations.ToList();
                List<LetterStatu> letterStatu = new List<LetterStatu>();
                letterStatu = db.LetterStatus.ToList();
                ViewBag.designationList = new SelectList(desingnation, "Name", "Name");
                ViewBag.letterStatusList = new SelectList(letterStatu, "Status", "Status");
            }
           
            return View();

        }
        [HttpPost]
        public ActionResult Commentpopup(Feedback model)
        {
            //if (ModelState.IsValid)
            {
               
                using (LetterManagementDBEntities db = new LetterManagementDBEntities())
                {
                    Letter pastLtter = db.Letters.Where(x => x.Id == model.Id).FirstOrDefault();
                    Feedback feedback = new Feedback();
                    feedback.StatusOfLetter = model.StatusOfLetter;
                    feedback.Assign = model.Assign;
                    feedback.Comment = model.Comment;
                    feedback.Responsible =pastLtter.Responsible;
                    feedback.Date = DateTime.Now;
                    feedback.LetterId = model.Id;
                    feedback.Responsible = pastLtter.Responsible;                                      
                    db.Feedbacks.Add(feedback);

                    pastLtter.Responsible = model.Assign;
                    db.SaveChanges();                   
                }
                return View("Index");
            }
           // ModelState.Clear();
            return View(model);
        }
        [HttpGet]
        public ActionResult AllFeedBack(int id)
        {
            var listFeedBackList = new FeedBackViewModel();
            using (LetterManagementDBEntities dc = new LetterManagementDBEntities())
            {
                List<Feedback> feedback = new List<Feedback>();               
                feedback = dc.Feedbacks.Where(x=>x.LetterId == id).ToList();
                ViewBag.FeedbackList = feedback;
            }
            
            return View();
           
        }
        public ActionResult LetterPreview(int id)
        {
            var LetterImage = new Letter();
            using (LetterManagementDBEntities db = new LetterManagementDBEntities())
            {
                LetterImage = db.Letters.Where(x => x.Id == id).FirstOrDefault();
               
            }

            return View(LetterImage);
        }

        public ActionResult AddNewSender(LetterViewModel model)
        {
            LetterFrom sender = new LetterFrom();
            using (LetterManagementDBEntities db = new LetterManagementDBEntities())
            {
                sender.LetterSender = model.Sender;
                db.LetterFroms.Add(sender);
                db.SaveChanges();               
            }
            return View("IncomingLetter");
        }   
    }
}

LMS/LMS/Views/LetterSending/AllFeedBack.cshtml
@model  LMS.Models.FeedBackViewModel
@{ 
    var feedlist = ViewBag.FeedbackList;
}
<table class="table">
    <thead>
        <tr>
            <th scope="col">DateOfComment</th>  
            <th scope="col">Responsible</th>                       
            <th scope="col">FeedBack</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in feedlist)
        {
            <tr>
                <td>@item.Date.ToString("dd MMM yyyy")</td>
                <td>@item.Responsible</td>
                <td>@item.Comment</td>
            </tr>            
        }
    </tbody>
</table>

  

LMS/LMS/Views/LetterSending/Commentpopup.cshtml
@model LMS.Context.Feedback

@using (Html.BeginForm("Commentpopup", "LetterSending", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="">
        <fieldset class="mb-3">
            @Html.AntiForgeryToken()
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-md-12 border-right p-2">
                    <div class="form-group row">
                        <label for="colFormLabelSm" class="col-sm-3 col-form-label LetterDate">Date</label>
                        <div class="col-lg-8">
                            @ViewBag.DateOfToday
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="colFormLabelSm" class="col-sm-3 col-form-label ReferenceNO">Ref.NO#</label>
                        <div class="col-lg-8">
                            @ViewBag.ReferenceNo
                        </div>
                    </div>                  
                    <div class="form-group row">
                        <label for="colFormLabelSm" class="col-sm-3 col-form-label ReferenceNO">Responsible</label>
                        <div class="col-lg-8">
                            @ViewBag.Responsible
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="colFormLabelSm" class="col-sm-3 col-form-label ReferenceNO">LetterStatus</label>
                        <div class="col-lg-8">
                            @Html.DropDownListFor(a => a.StatusOfLetter, ViewBag.letterStatusList as SelectList, "--Select status--", new { @class = "form-control" })
                            @Html.ValidationMessageFor(a => a.StatusOfLetter, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="colFormLabelSm" class="col-sm-3 col-form-label BranchId">Assign</label>
                        <div class="col-lg-8">                         
                            @Html.DropDownListFor(a => a.Assign, ViewBag.designationList as SelectList, "--Select a Person--", new { @class = "form-control" })
                            @Html.ValidationMessageFor(a => a.Assign, "", new { @class = "text-danger" })                          
                        </div>
                    </div>
                    
                    <div class="form-group row">
                        <label for="colFormLabelSm" class="col-sm-3 col-form-label LetterType">FeedBack</label>
                        <div class="col-lg-8">
                            @Html.TextAreaFor(a => a.Comment, new { @class = "form-control", @placeholder = "Write a comment" })
                            @Html.ValidationMessageFor(a => a.Comment, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div>
                        <button type="submit" class="btn btn-primary">Submit</button>                     
                    </div>
                </div>
            </div>
        </fieldset>  
    </div>
}

LMS/LMS/Views/LetterSending/IncomingLetter.cshtml
@model LMS.Models.LetterViewModel
@{
    ViewBag.Title = "IncomingLetter";
    Layout = "~/Views/Shared/_masterlayout.cshtml";
}

<link href="~/Content/form.css" rel="stylesheet" />


@using (Html.BeginForm("IncomingLetter", "LetterSending", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="">
        <fieldset class="mb-3">
            @Html.AntiForgeryToken()
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-md-6 border-right p-2">
                    <div class="form-group row LetterFrom">
                        <label for="colFormLabelSm" class="col-sm-3 col-form-label ">Letter From</label>
                        <div class="col-lg-7">
                            <a href="/LetterSending/AddNewSender" class="btn btn-dark " data-toggle="modal" data-target="#myModal">add</a>
                            @Html.DropDownListFor(a => a.Sender, ViewBag.letterfromList as SelectList, "--Select Sender--", new { @class = "form-control" })
                            <div class="modal fade" id="myModal">
                                <div class="modal-dialog">
                                     <div class="modal-content">
                                         
                                         <div class="modal-header">
                                             <h5 class="modal-title">Add New Sender Name</h5>
                                             <a href="#" class="close" data-dissmiss="modal">&times;</a>
                                         </div>
                                         <div class="modal-body">
                                            <form id="myForm">
                                                <div class="form-group row">
                                                    <label for="colFormLabelSm" class="col-sm-3 col-form-label Subject">Sender Name</label>
                                                    <div class="col-lg-8">
                                                        @Html.TextBoxFor(a => a.Sender, new { @class = "form-control", @placeholder = "Sender" })
                                                        @Html.ValidationMessageFor(a => a.Sender, "", new { @class = "text-danger" })
                                                    </div>
                                                </div>
                                            </form>
                                             <div>

                                             </div>
                                         </div>
                                         <div class="modal-footer">
                                             <a href="#" class="btn btn-danger" data-dissmiss="modal">Cancel</a>
                                             <input type="button" onclick="location.href='@Url.Action("AddNewSender","LetterSending")'" />
                                         </div>
     
                                     </div>
                                </div>
                            </div>                         
                            @Html.ValidationMessageFor(a => a.Sender,"",new {@class="text-danger" })
                        </div>
                    </div>
                    
                    <div class="form-group row">
                        <label for="colFormLabelSm" class="col-sm-3 col-form-label Subject">Subject</label>
                        <div class="col-lg-8">
                            @Html.TextBoxFor(a => a.Subject, new { @class = "form-control", @placeholder = "Subject" })
                            @Html.ValidationMessageFor(a => a.Subject, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="colFormLabelSm" class="col-sm-3 col-form-label ReferenceNO">Reference NO.#</label>
                        <div class="col-lg-8">
                            @Html.TextBoxFor(a => a.ReferenceNo, new { @class = "form-control", @placeholder = "Reference number" })
                            @Html.ValidationMessageFor(a => a.ReferenceNo, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="colFormLabelSm" class="col-sm-3 col-form-label LetterDate">Letter Date</label>
                        <div class="col-lg-8">
                            @Html.EditorFor(model => model.LetterDate, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.LetterDate, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="colFormLabelSm" class="col-sm-3 col-form-label ReceiveDate">Receive Date</label>
                        <div class="col-lg-8">
                            @Html.EditorFor(model => model.ReceiveDate, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ReceiveDate, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6 border-left p-2">
                    
                    <div class="form-group row">
                        <label for="colFormLabelSm" class="col-sm-3 col-form-label RecipientId">Assign</label>
                        <div class="col-lg-8">
                           @Html.DropDownListFor(a=>a.Responsible, ViewBag.designationList as SelectList,"--Select a Person--",new { @class="form-control"})
                           @Html.ValidationMessageFor(a => a.Responsible, "", new { @class = "text-danger" }  )
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="colFormLabelSm" class="col-sm-3 col-form-label LetterType">Letter Type</label>
                        <div class="col-lg-7">
                            @Html.DropDownListFor(a => a.Type, ViewBag.LettertypeList as SelectList, "--Select letter type--", new { @class = "form-control" })
                            @Html.ValidationMessageFor(a => a.Type, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="colFormLabelSm" class="col-sm-3 col-form-label LetterStatusId">Letter Status</label>
                        <div class="col-lg-8">
                            @Html.DropDownListFor(a => a.StatusOfLetter, ViewBag.letterStatusList as SelectList, "--Select status--", new { @class = "form-control" })
                            @Html.ValidationMessageFor(a => a.StatusOfLetter, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="colFormLabelSm" class="col-sm-3 col-form-label LetterStatusId"> Upload Image</label>
                        <input type="file" name="ImageFile">
                    </div>
                    <button type="submit" class="btn btn-primary btn-md btn-block">Submit</button>

                </div>
            </div>
        </fieldset>

    </div>
    <script>
    $(document).ready(function () {
        $("#btnSubmit").click(function () {
            var myformdata = ("#myForm").serialize();
                $.ajax({
                    type: "POST",
                    url: "/LetterSending/AddNewSender",
                    data: myformdata,
                    success: function () {
                        $("#myModal").modal("hide");
                    }
                })
        })
    })
    </script>
}

LMS/LMS/Views/LetterSending/Index.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.13/css/jquery.dataTables.min.css" />
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <style>
        span.field-validation-error {
            color: red;
        }
    </style>
</head>
<body>
    <br />
    <div style="width:90%; margin:0 auto" class="tablecontainer">
        <table id="myDatatable">
            <thead>
                <tr>
                    <th>LetterFrom</th>
                    <th>Subject</th>
                    <th>ReceiveDate</th>
                    <th>LetterStatus</th>
                    <th>Assigned</th>
                    <th>PreviewLetter</th>
                    <th>Reassign</th>
                    <th>AllFeedback</th>
                </tr>
            </thead>
        </table>
    </div>

    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.10/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>


    <script>
        $(document).ready(function () {
            var oTable = $('#myDatatable').DataTable({
                "ajax": {
                    "url": '/LetterSending/ViewAllIncomingLetter',
                    "type" : "get",
                    "datatype" : "json"
                },
                "columns": [
                    { "data": "Sender", "autoWidth": true },
                    { "data": "Subject", "autoWidth": true },
                    //{ "data": "ReceiveDate", "autoWidth": true },
                     {  
                         'data': 'ReceiveDate',
                         'render': function (jsonDate) {
                             var date = new Date(parseInt(jsonDate.substr(6)));
                             var month = ("0" + (date.getMonth() + 1)).slice(-2);
                             return ("0" + date.getDate()).slice(-2) + '-' + month + '-' + date.getFullYear();
                         }
                     },
                    { "data": "StatusOfLetter", "autoWidth": true },
                    { "data": "Responsible", "autoWidth": true },
                    {
                        "data": "Id", "width": "50px", "render": function (data) {
                            return '<a class="popup btn btn-info" href="/LetterSending/LetterPreview/' + data + '">Click</a>';
                        }
                    },
                    {
                        "data": "Id", "width": "50px", "render": function (data) {
                            return '<a class="popup btn btn-primary" href="/LetterSending/Commentpopup/' + data + '">Click</a>';
                        }
                    },

                    {
                        "data": "Id", "width": "50px", "render": function (data) {
                            return '<a class="popup btn btn-success" href="/LetterSending/AllFeedBack/' + data + '">Click</a>';
                        }
                    }
                ]
            })
            $('.tablecontainer').on('click', 'a.popup', function (e) {
                e.preventDefault();
                OpenPopup($(this).attr('href'));
            })
            function OpenPopup(pageUrl) {
                var $pageContent = $('<div/>');
                $pageContent.load(pageUrl, function () {
                    $('#popupForm', $pageContent).removeData('validator');
                    $('#popupForm', $pageContent).removeData('unobtrusiveValidation');
                    $.validator.unobtrusive.parse('form');

                });

                $dialog = $('<div class="popupWindow" style="overflow:auto"></div>')
                          .html($pageContent)
                          .dialog({
                              draggable : false,
                              autoOpen : false,
                              resizable : false,
                              model : true,
                              title:'INFORMATION',
                              height : 400,
                              width : 500,
                              close: function () {
                                  $dialog.dialog('destroy').remove();
                              }
                          })

                $('.popupWindow').on('submit', '#popupForm', function (e) {
                    var url = $('#popupForm')[0].action;
                    $.ajax({
                        type : "POST",
                        url : url,
                        data: $('#popupForm').serialize(),
                        success: function (data) {
                            if (data.status) {
                                $dialog.dialog('close');
                                oTable.ajax.reload();
                            }
                        }
                    })

                    e.preventDefault();
                })
                $dialog.dialog('open');
            }
        })
    </script>
</body>
</html>

LMS/LMS/Views/LetterSending/LetterPreview.cshtml
@model LMS.Context.Letter

@{
    Layout = null;
}

<!DOCTYPE html>
<img src="@Url.Content(Model.ScannedImage)" height="500" width="500"/>
  